project:
  type: website

website:
  title: "Amay's blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/amay1212
      - icon: twitter
        href: https://twitter.com
format:
  html:
    embed-resources: true
    smooth-scroll: true
    theme: cosmo
    fontcolor: black
    toc: true
    toc-location: left
    toc-title: Summary
    toc-depth: 3
    css: styles.css



